name: Auto Approve PRs

on:
  pull_request:
    types:
      - opened

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'github-actions[bot]'
    steps:
      - name: Auto approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.AUTO_APPROVE_TOKEN }}
